- type: entity
  parent: MindRoleGhostRoleNeutral
  id: MindRoleGhostCorporateAligned
  name: Ghost Role (Corporate Aligned)
  components:
    - type: MindRole
      roleType: CorporateAligned

# Embedded Agent
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleEmbeddedAgent
  name: Embedded Agent Role
  components:
    - type: MindRole
      antagPrototype: Thief
      subtype: role-subtype-embeddedagent
    - type: EmbeddedAgent