# Reference Resources/Prototypes/Roles/Antags/nukeops.yml for Nuclear Operative setup. This antag will function similarly
- type: antag
  id: Scavenger
  name: roles-antag-scavenger-name
  antagonist: true
  setPreference: true
  objective: roles-antag-scavenger-objective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24h STARLIGHT
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6h STARLIGHT
  guides: [ NuclearOperatives ]
  previewStartingGear: SyndicateOperativeGearFull

- type: antag
  id: ScavengerBoss
  name: roles-antag-scavenger-boss-name
  antagonist: true
  setPreference: true
  objective: roles-antag-scavenger-boss-objective
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24h STARLIGHT
    - !type:DepartmentTimeRequirement
      department: Security
      time: 43200 # 12h STARLIGHT
    - !type:DepartmentTimeRequirement
      department: Command
      time: 21600 # 6h STARLIGHT
  guides: [ NuclearOperatives ]
  previewStartingGear: SyndicateCommanderGearFull

- type: startingGear
  id: ScavengerGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
      - WeaponPistolViper
      - PinpointerSyndicateNuclear
      - DeathAcidifierImplanter

#Scavenger Gear
- type: startingGear
  id: ScavengerGearFull
  parent: ScavengerGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio40TC

- type: chameleonOutfit
  id: ScavengerOutfit
  name: roles-antag-scavenger-name
  startingGear: ScavengerGearFullNoUplink
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Scavenger Boss Gear
- type: startingGear
  id: ScavengerBossGearFull
  parent: ScavengerGearFull
  equipment:
    neck: CommanderWhistle #Starlight
    ears: ClothingHeadsetAltSyndicateCommander #Starlight
    outerClothing: ClothingOuterHardsuitSyndieCommander
    id: CommanderPDA
#  inhand:
#    - NukeOpsDeclarationOfWar

- type: chameleonOutfit
  id: ScavengerBossOutfit
  name: roles-antag-scavenger-boss-name
  startingGear: ScavengerBossGearFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen

#Lone Scavenger Gear
- type: startingGear
  id: ScavengerLoneGearFull
  parent: ScavengerGearFull
  equipment:
    pocket2: BaseUplinkRadio60TC

# Spawners
#- type: entity
#  name: scavenger boss spawner
#  id: SpawnPointScavengerBoss
#  parent: MarkerBase
#  components:
#    - type: SpawnPoint
#    - type: Sprite
#      sprite: Markers/jobs.rsi
#      layers:
#        - state: green
#        - sprite: Structures/Wallmounts/signs.rsi
#          state: danger

- type: entity
  name: scavenger spawner
  id: SpawnPointScavs
  parent: MarkerBase
  components:
    - type: SpawnPoint
    - type: Sprite
      sprite: Markers/jobs.rsi
      layers:
        - state: green
        - sprite: Structures/Wallmounts/signs.rsi
          state: danger